# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        uses: docker/login-action@v1.10.0
        with:
          # Username used to log against the Docker registry
          username: viniciosaguiar
          # Password or personal access token used to log against the Docker registry
          password: nexozero02
      - name: Docker Images Build And Push
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          # Docker Registry Url, eg: registry.xxxxx.cs.com
          registry_url: https://hub.docker.com
          # Docker Image Namespaces, eg: adotcode
          namespaces: viniciosaguiar
          # Docker Image Repository Name, eg: adc.ms.eureka
          repository_name: rotten-potatoes
          # Docker Login UserName, from: https://cr.console..com/
          user_name: viniciosaguiar 
          # Docker Login Password, from: https://cr.console..com/
          password: nexozero02
          # Image Build Version
          image_version: v3
          # Docker File Directory, Default Current Directory (.)
          docker_file: ./src/Dockerfile

        
        
