# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Docker Build & Push Action
  # You may pin to the exact commit or the version.
  # uses: mr-smithers-excellent/docker-build-push@a7fe6652db5c7274374844e81692992f5a2befb9
        uses: mr-smithers-excellent/docker-build-push@v5.6
        with:
          # Name of the Docker image
          image: rotten-potatoes
          # Tags override for Docker image
          tags: viniciosaguiar/rotten-potatoes:v4
          # Target Docker registry
          registry: https://hub.docker.com/
          # Location of Dockerfile, if not Dockerfile in root directory
          dockerfile: ./src
          # Directory to run `docker build` from, if not project root
          directory: ./src
          # Docker registry username
          username: viniciosaguiar
          # Docker registry password
          password: nexozero02
          
          
          

